### ISSUE TITLE
Connection to CR1000 with RS485 connection 

### ISSUE THREAD

**Issue by VincentBourgeois** [LionelDarras/PyCampbellCR1000#1]
Hello,
I don't know if is a good place for a question.

I want to get file in 4 CR1000 datalogger.
Datalogger are connected as shown in the following "diagram".
__________________________________________________
-> CR1000 1 (pakbus : 1) with TCP connection
    -> CR1000 2 (pakbus : 2) with RS485 connection to CR1000 1
    -> CR1000 3 (pakbus : 3) with RS485 connection to CR1000 1
    -> CR1000 4 (pakbus : 4) with RS485 connection to CR1000 1
__________________________________________________
I have one CR1000 connected in TCP and 3 connected with a bus RS485 to the first CR1000. Each datalogger have a PakBus adress.
I can connect to all CR1000 with LoggerNet.

For get file of the first datalogger, I execute "pycr1000 getfile tcp:192.168.1.20:6785 CPU:FILE.CR1 CPU:FILE.CR1" without problem.
For other datalogger, I try "pycr1000 getfile tcp:192.168.1.20:6785 CPU:FILE.CR1 CPU:FILE.CR1 --dest 2" but I have an error "pycr1000: error: Can not access to device".
I try also an easier request "pycr1000 gettime tcp:192.168.1.20:6785 --dest 2" but I have the same error.

Is it possible to get file in this configuration ?
Can I execute another command ?
Is it a bug or is it a new feature ?

Tank you

Best regards

**Comment by LionelDarras** [comment]
Hi,
I see your message today only.
It's the last bug of this driver. It's a problem about the packbus number: when we developped it, we had only one CR1000 and it's packbus number was always 1... I don't have one CR1000 to debug this problem. I try to find a CR1000 to test it and i keep you in touch.
Can you try yours commands with the option "--debug" and send me the result displayed ?

Best regards

**Comment by VincentBourgeois** [comment]
Hi,

Thanks for your interests.

Debug communication to datalogger 1 is :
pycr1000 gettime tcp:192.168.1.20:6785 --dest 1 --debug
2016-05-12 07:26:19,889 INFO: init client 
2016-05-12 07:26:19,890 INFO: Get the node attention 
2016-05-12 07:26:19,891 INFO: Wait packet with transaction None 
2016-05-12 07:26:19,997 INFO: Read packet: EF FF 10 01 0F FF 00 01 0E 00 DD F0 
2016-05-12 07:26:19,998 INFO: Unquote packet 
2016-05-12 07:26:19,998 INFO: Check signature : OK 
2016-05-12 07:26:19,999 INFO: Decode packet 
2016-05-12 07:26:19,999 INFO: HiProtoCode, MsgType = <0, e> 
2016-05-12 07:26:20,000 INFO: Create header 
2016-05-12 07:26:20,001 INFO: Packet data: 90 01 58 02 00 01 08 02 09 01 00 02 07 08 
2016-05-12 07:26:20,001 INFO: Calculate signature for packet 
2016-05-12 07:26:20,002 INFO: Calculate signature nullifier to create packet 
2016-05-12 07:26:20,002 INFO: Quote packet 
2016-05-12 07:26:20,003 INFO: Write: BD 90 01 58 02 00 01 08 02 09 01 00 02 07 08 F6 86 BD 
2016-05-12 07:26:20,004 INFO: Wait packet with transaction 1 
2016-05-12 07:26:20,016 INFO: Read packet: A8 02 10 01 08 02 00 01 89 01 00 02 07 08 24 56 
2016-05-12 07:26:20,017 INFO: Unquote packet 
2016-05-12 07:26:20,017 INFO: Check signature : OK 
2016-05-12 07:26:20,018 INFO: Decode packet 
2016-05-12 07:26:20,018 INFO: HiProtoCode, MsgType = <0, 89> 
2016-05-12 07:26:20,019 INFO: Create header 
2016-05-12 07:26:20,020 INFO: Packet data: 90 01 58 02 00 01 08 02 09 02 00 02 07 08 
2016-05-12 07:26:20,020 INFO: Calculate signature for packet 
2016-05-12 07:26:20,021 INFO: Calculate signature nullifier to create packet 
2016-05-12 07:26:20,021 INFO: Quote packet 
2016-05-12 07:26:20,022 INFO: Write: BD 90 01 58 02 00 01 08 02 09 02 00 02 07 08 AF 69 BD 
2016-05-12 07:26:20,023 INFO: Wait packet with transaction 2 
2016-05-12 07:26:20,035 INFO: Read packet: A8 02 10 01 08 02 00 01 89 02 00 02 07 08 DE 39 
2016-05-12 07:26:20,036 INFO: Unquote packet 
2016-05-12 07:26:20,036 INFO: Check signature : OK 
2016-05-12 07:26:20,037 INFO: Decode packet 
2016-05-12 07:26:20,037 INFO: HiProtoCode, MsgType = <0, 89> 
2016-05-12 07:26:20,038 INFO: Try gettime 
2016-05-12 07:26:20,039 INFO: Create header 
2016-05-12 07:26:20,039 INFO: Packet data: A0 01 98 02 10 01 08 02 17 03 00 00 00 00 00 00 00 00 00 00 
2016-05-12 07:26:20,040 INFO: Calculate signature for packet 
2016-05-12 07:26:20,040 INFO: Calculate signature nullifier to create packet 
2016-05-12 07:26:20,041 INFO: Quote packet 
2016-05-12 07:26:20,041 INFO: Write: BD A0 01 98 02 10 01 08 02 17 03 00 00 00 00 00 00 00 00 00 00 8F 06 BD 
2016-05-12 07:26:20,042 INFO: Wait packet with transaction 3 
2016-05-12 07:26:20,055 INFO: Read packet: A8 02 10 01 18 02 00 01 97 03 00 31 95 92 9C 00 98 96 80 F3 C2 
2016-05-12 07:26:20,055 INFO: Unquote packet 
2016-05-12 07:26:20,056 INFO: Check signature : OK 
2016-05-12 07:26:20,056 INFO: Decode packet 
2016-05-12 07:26:20,057 INFO: HiProtoCode, MsgType = <1, 97> 
2016-05-12 07:26:20
2016-05-12 07:26:20,058 INFO: Send bye command 
2016-05-12 07:26:20,058 INFO: Create header 
2016-05-12 07:26:20,059 INFO: Packet data: B0 01 18 02 00 01 08 02 0D 00 
2016-05-12 07:26:20,059 INFO: Calculate signature for packet 
2016-05-12 07:26:20,060 INFO: Calculate signature nullifier to create packet 
2016-05-12 07:26:20,060 INFO: Quote packet 
2016-05-12 07:26:20,061 INFO: Write: BD B0 01 18 02 00 01 08 02 0D 00 50 6D BD 

Debug communication to datalogger 2 is :
pycr1000 gettime tcp:192.168.1.20:6785 --dest 2 --debug
2016-05-12 07:26:53,589 INFO: init client 
2016-05-12 07:26:53,590 INFO: Get the node attention 
2016-05-12 07:26:53,591 INFO: Wait packet with transaction None 
2016-05-12 07:26:53,797 INFO: Read packet: EF FF 10 01 0F FF 00 01 0E 00 DD F0 
2016-05-12 07:26:53,798 INFO: Unquote packet 
2016-05-12 07:26:53,798 INFO: Check signature : OK 
2016-05-12 07:26:53,799 INFO: Decode packet 
2016-05-12 07:26:53,799 INFO: HiProtoCode, MsgType = <0, e> 
2016-05-12 07:26:53,800 INFO: Create header 
2016-05-12 07:26:53,801 INFO: Packet data: 90 02 58 02 00 02 08 02 09 01 00 02 07 08 
2016-05-12 07:26:53,801 INFO: Calculate signature for packet 
2016-05-12 07:26:53,802 INFO: Calculate signature nullifier to create packet 
2016-05-12 07:26:53,802 INFO: Quote packet 
2016-05-12 07:26:53,803 INFO: Write: BD 90 02 58 02 00 02 08 02 09 01 00 02 07 08 39 99 BD 
2016-05-12 07:26:53,804 INFO: Wait packet with transaction 1 
2016-05-12 07:27:14,015 INFO: Create header 
2016-05-12 07:27:14,016 INFO: Packet data: 90 02 58 02 00 02 08 02 09 02 00 02 07 08 
2016-05-12 07:27:14,017 INFO: Calculate signature for packet 
2016-05-12 07:27:14,018 INFO: Calculate signature nullifier to create packet 
2016-05-12 07:27:14,019 INFO: Quote packet 
2016-05-12 07:27:14,019 INFO: Write: BD 90 02 58 02 00 02 08 02 09 02 00 02 07 08 F4 7D BD 
2016-05-12 07:27:14,021 INFO: Wait packet with transaction 2 
2016-05-12 07:27:14,196 INFO: Read packet: EF FF 10 01 0F FF 00 01 0E 00 DD F0 
2016-05-12 07:27:14,197 INFO: Unquote packet 
2016-05-12 07:27:14,198 INFO: Check signature : OK 
2016-05-12 07:27:14,198 INFO: Decode packet 
2016-05-12 07:27:14,199 INFO: HiProtoCode, MsgType = <0, e> 
2016-05-12 07:27:14,410 INFO: Create header 
2016-05-12 07:27:14,412 INFO: Packet data: 90 02 58 02 00 02 08 02 09 03 00 02 07 08 
2016-05-12 07:27:14,412 INFO: Calculate signature for packet 
2016-05-12 07:27:14,413 INFO: Calculate signature nullifier to create packet 
2016-05-12 07:27:14,413 INFO: Quote packet 
2016-05-12 07:27:14,414 INFO: Write: BD 90 02 58 02 00 02 08 02 09 03 00 02 07 08 AE 60 BD 
2016-05-12 07:27:14,415 INFO: Wait packet with transaction 3 
2016-05-12 07:27:14,603 INFO: Read packet: EF FF 10 01 0F FF 00 01 0E 00 DD F0 
2016-05-12 07:27:14,603 INFO: Unquote packet 
2016-05-12 07:27:14,604 INFO: Check signature : OK 
2016-05-12 07:27:14,605 INFO: Decode packet 
2016-05-12 07:27:14,605 INFO: HiProtoCode, MsgType = <0, e> 
Traceback (most recent call last):
  File "/usr/local/bin/pycr1000", line 9, in <module>
    load_entry_point('PyCampbellCR1000==0.4', 'console_scripts', 'pycr1000')()
  File "/usr/local/lib/python2.7/dist-packages/PyCampbellCR1000-0.4-py2.7.egg/pycampbellcr1000/__main__.py", line 254, in main
    args.code)
  File "/usr/local/lib/python2.7/dist-packages/PyCampbellCR1000-0.4-py2.7.egg/pycampbellcr1000/device.py", line 67, in from_url
    return cls(link, dest_node, src_node,security_code)     #EGC Add security code to the constructor call
  File "/usr/local/lib/python2.7/dist-packages/PyCampbellCR1000-0.4-py2.7.egg/pycampbellcr1000/device.py", line 52, in __init__
    raise NoDeviceException()
pycampbellcr1000.exceptions.NoDeviceException: Can not access to device.
2016-05-12 07:27:14,835 INFO: Send bye command 


I have see in documentation PakBus (https://s.campbellsci.com/documents/de/manuals/pakbusnetguide.pdf), header PakBus packet have "Destination physical address" and "Destination node ID".
I try with LoggerNet to communicate to my datalogger 2 and I see the log. With LoggerNet
PakBus packet header have "Destination physical address" = 1 and "Destination node ID" = 2 while with "pycr1000" PakBus packet header have "Destination physical address" = 2 and "Destination node ID" = 2. 
I think it is a possible solution.

Best regards.

**Comment by LionelDarras** [comment]
I can have access to a Campbell cr1000 the May 25th.
I think that i understood the matter, but sorry, i can't solve this problem before this date.
When i solve this bug, i keep you in touch !
Best regards.

**Comment by LionelDarras** [comment]
Hi,
I did some modifications in source code to dissociate the physical address and the node of the source and destination (src_addr, src_node, dest_addr, dest_node).
I have only one CR1000 on my possession so it's difficult to me to test it really because it's when several CR1000 are linked than the matter occurs.
Please, download the new code source, install it with "python setup.py install", and try it replacing "--dest" by "--dest_node" in your command, like this:
"pycr1000 getfile tcp:192.168.1.20:6785 CPU:FILE.CR1 CPU:FILE.CR1 --dest_node 2",
and tell me if it functions or not ! Thanks.
Best regards.

**Comment by VincentBourgeois** [comment]
Hi,
Thank you for your modification.
I cannot test the new program, because I have no access to my CR1000 the next two week.
When I can, I test and I tell you if it function.
Thanks
Best regards

**Comment by VincentBourgeois** [comment]
Hello,
I have no try new program before because connection between CR1000 was broken. It is now resolved.

I have test the new program to the CR1000 with pakbus 1 without routing. It is OK.
pycr1000 getfile tcp:192.168.1.20:6785 CPU:MES_F1_0.dat CPU:MES_F1_0.dat --dest_node 1 --debug
2016-07-11 12:24:55,563 INFO: init client 
2016-07-11 12:24:55,563 INFO: Get the node attention 
2016-07-11 12:24:55,564 INFO: Wait packet with transaction None 
2016-07-11 12:24:55,579 INFO: Read packet: EF FF 10 01 0F FF 00 01 0E 00 DD F0 
2016-07-11 12:24:55,580 INFO: Unquote packet 
2016-07-11 12:24:55,581 INFO: Check signature : OK 
2016-07-11 12:24:55,581 INFO: Decode packet 
2016-07-11 12:24:55,582 INFO: HiProtoCode, MsgType = <0, e> 
2016-07-11 12:24:55,582 INFO: Create header 
2016-07-11 12:24:55,583 INFO: Packet data: 90 01 58 02 00 01 08 02 09 01 00 02 07 08 
2016-07-11 12:24:55,584 INFO: Calculate signature for packet 
2016-07-11 12:24:55,584 INFO: Calculate signature nullifier to create packet 
2016-07-11 12:24:55,585 INFO: Quote packet 
2016-07-11 12:24:55,585 INFO: Write: BD 90 01 58 02 00 01 08 02 09 01 00 02 07 08 F6 86 BD 
2016-07-11 12:24:55,586 INFO: Wait packet with transaction 1 
2016-07-11 12:24:55,600 INFO: Read packet: A8 02 10 01 08 02 00 01 89 01 01 02 07 08 07 4A 
2016-07-11 12:24:55,601 INFO: Unquote packet 
2016-07-11 12:24:55,602 INFO: Check signature : OK 
2016-07-11 12:24:55,602 INFO: Decode packet 
2016-07-11 12:24:55,603 INFO: HiProtoCode, MsgType = <0, 89> 
2016-07-11 12:24:55,603 INFO: Try get file 
2016-07-11 12:24:55,604 INFO: Create header 
2016-07-11 12:24:55,605 INFO: Packet data: 90 01 58 02 00 01 08 02 09 02 00 02 07 08 
2016-07-11 12:24:55,605 INFO: Calculate signature for packet 
2016-07-11 12:24:55,606 INFO: Calculate signature nullifier to create packet 
2016-07-11 12:24:55,606 INFO: Quote packet 
2016-07-11 12:24:55,607 INFO: Write: BD 90 01 58 02 00 01 08 02 09 02 00 02 07 08 AF 69 BD 
2016-07-11 12:24:55,607 INFO: Wait packet with transaction 2 
2016-07-11 12:24:55,620 INFO: Read packet: A8 02 10 01 08 02 00 01 89 02 01 02 07 08 C1 2D 
2016-07-11 12:24:55,621 INFO: Unquote packet 
2016-07-11 12:24:55,621 INFO: Check signature : OK 
2016-07-11 12:24:55,622 INFO: Decode packet 
2016-07-11 12:24:55,622 INFO: HiProtoCode, MsgType = <0, 89> 
2016-07-11 12:24:55,623 INFO: Create header 
2016-07-11 12:24:55,624 INFO: Packet data: A0 01 98 02 10 01 08 02 1D 03 00 00 43 50 55 3A 4D 45 53 5F 46 31 5F 30 2E 64 61 74 00 00 00 00 00 00 02 00 
2016-07-11 12:24:55,624 INFO: Calculate signature for packet 
2016-07-11 12:24:55,625 INFO: Calculate signature nullifier to create packet 
2016-07-11 12:24:55,625 INFO: Quote packet 
2016-07-11 12:24:55,626 INFO: Write: BD A0 01 98 02 10 01 08 02 1D 03 00 00 43 50 55 3A 4D 45 53 5F 46 31 5F 30 2E 64 61 74 00 00 00 00 00 00 02 00 ED 75 BD 
2016-07-11 12:24:55,627 INFO: Wait packet with transaction 3 
2016-07-11 12:24:55,651 INFO: Read packet: A8 02 10 01 18 02 00 01 9D 03 0E 00 00 00 00 75 F0 
2016-07-11 12:24:55,652 INFO: Unquote packet 
2016-07-11 12:24:55,652 INFO: Check signature : OK 
2016-07-11 12:24:55,653 INFO: Decode packet 
2016-07-11 12:24:55,653 INFO: HiProtoCode, MsgType = <1, 9d> 
2016-07-11 12:24:55,654 INFO: Send bye command 
2016-07-11 12:24:55,655 INFO: Create header 
2016-07-11 12:24:55,655 INFO: Packet data: B0 01 18 02 00 01 08 02 0D 00 
2016-07-11 12:24:55,656 INFO: Calculate signature for packet 
2016-07-11 12:24:55,656 INFO: Calculate signature nullifier to create packet 
2016-07-11 12:24:55,657 INFO: Quote packet 
2016-07-11 12:24:55,657 INFO: Write: BD B0 01 18 02 00 01 08 02 0D 00 50 6D BD 

But when I try to the CR1000 with pakbus 2 and with routing, I have an error.
pycr1000 getfile tcp:192.168.1.20:6785 CPU:MES_F2_0.dat CPU:MES_F2_0.dat --dest_node 2 --debug
2016-07-11 12:25:47,027 INFO: init client 
2016-07-11 12:25:47,028 INFO: Get the node attention 
2016-07-11 12:25:47,029 INFO: Wait packet with transaction None 
2016-07-11 12:25:47,172 INFO: Read packet: EF FF 10 01 0F FF 00 01 0E 00 DD F0 
2016-07-11 12:25:47,173 INFO: Unquote packet 
2016-07-11 12:25:47,173 INFO: Check signature : OK 
2016-07-11 12:25:47,174 INFO: Decode packet 
2016-07-11 12:25:47,174 INFO: HiProtoCode, MsgType = <0, e> 
2016-07-11 12:25:47,175 INFO: Create header 
2016-07-11 12:25:47,176 INFO: Packet data: 90 01 58 02 00 02 08 02 09 01 00 02 07 08 
2016-07-11 12:25:47,176 INFO: Calculate signature for packet 
2016-07-11 12:25:47,177 INFO: Calculate signature nullifier to create packet 
2016-07-11 12:25:47,177 INFO: Quote packet 
2016-07-11 12:25:47,178 INFO: Write: BD 90 01 58 02 00 02 08 02 09 01 00 02 07 08 A5 AA BD 
2016-07-11 12:25:47,179 INFO: Wait packet with transaction 1 
2016-07-11 12:25:47,196 INFO: Read packet: A8 02 70 01 08 02 00 01 09 DC 01 02 07 08 7B FC 
2016-07-11 12:25:47,196 INFO: Unquote packet 
2016-07-11 12:25:47,197 INFO: Check signature : OK 
2016-07-11 12:25:47,197 INFO: Decode packet 
2016-07-11 12:25:47,198 INFO: HiProtoCode, MsgType = <0, 9> 
2016-07-11 12:25:47,409 INFO: Create header 
2016-07-11 12:25:47,410 INFO: Packet data: 90 01 58 02 00 02 08 02 09 02 00 02 07 08 
2016-07-11 12:25:47,411 INFO: Calculate signature for packet 
2016-07-11 12:25:47,411 INFO: Calculate signature nullifier to create packet 
2016-07-11 12:25:47,412 INFO: Quote packet 
2016-07-11 12:25:47,412 INFO: Write: BD 90 01 58 02 00 02 08 02 09 02 00 02 07 08 5F 8D BD 
2016-07-11 12:25:47,413 INFO: Wait packet with transaction 2 
2016-07-11 12:25:47,570 INFO: Read packet: EF FF 10 01 0F FF 00 01 0E 00 DD F0 
2016-07-11 12:25:47,571 INFO: Unquote packet 
2016-07-11 12:25:47,571 INFO: Check signature : OK 
2016-07-11 12:25:47,572 INFO: Decode packet 
2016-07-11 12:25:47,573 INFO: HiProtoCode, MsgType = <0, e> 
2016-07-11 12:25:47,785 INFO: Create header 
2016-07-11 12:25:47,786 INFO: Packet data: 90 01 58 02 00 02 08 02 09 03 00 02 07 08 
2016-07-11 12:25:47,787 INFO: Calculate signature for packet 
2016-07-11 12:25:47,787 INFO: Calculate signature nullifier to create packet 
2016-07-11 12:25:47,788 INFO: Quote packet 
2016-07-11 12:25:47,789 INFO: Write: BD 90 01 58 02 00 02 08 02 09 03 00 02 07 08 18 70 BD 
2016-07-11 12:25:47,790 INFO: Wait packet with transaction 3 
2016-07-11 12:25:47,970 INFO: Read packet: EF FF 10 01 0F FF 00 01 0E 00 DD F0 
2016-07-11 12:25:47,971 INFO: Unquote packet 
2016-07-11 12:25:47,972 INFO: Check signature : OK 
2016-07-11 12:25:47,973 INFO: Decode packet 
2016-07-11 12:25:47,973 INFO: HiProtoCode, MsgType = <0, e> 
Traceback (most recent call last):
  File "/usr/local/bin/pycr1000", line 9, in <module>
    load_entry_point('PyCampbellCR1000==0.4', 'console_scripts', 'pycr1000')()
  File "/usr/local/lib/python2.7/dist-packages/PyCampbellCR1000-0.4-py2.7.egg/pycampbellcr1000/__main__.py", line 258, in main
    args.src_addr, args.src_node, args.code)
  File "/usr/local/lib/python2.7/dist-packages/PyCampbellCR1000-0.4-py2.7.egg/pycampbellcr1000/device.py", line 71, in from_url
    return cls(link, dest_addr, dest_node, src_addr, src_node, security_code)     #EGC Add security code to the constructor call
  File "/usr/local/lib/python2.7/dist-packages/PyCampbellCR1000-0.4-py2.7.egg/pycampbellcr1000/device.py", line 54, in __init__
    raise NoDeviceException()
pycampbellcr1000.exceptions.NoDeviceException: Can not access to device.
2016-07-11 12:25:48,207 INFO: Send bye command 

I have also try with "dest_addr"
pycr1000 getfile tcp:192.168.1.20:6785 CPU:MES_F2_0.dat CPU:MES_F2_0.dat --dest_addr 1 --dest_node 2 --debug
2016-07-11 12:33:06,501 INFO: init client 
2016-07-11 12:33:06,502 INFO: Get the node attention 
2016-07-11 12:33:06,503 INFO: Wait packet with transaction None 
2016-07-11 12:33:06,610 INFO: Read packet: EF FF 10 01 0F FF 00 01 0E 00 DD F0 
2016-07-11 12:33:06,610 INFO: Unquote packet 
2016-07-11 12:33:06,611 INFO: Check signature : OK 
2016-07-11 12:33:06,611 INFO: Decode packet 
2016-07-11 12:33:06,612 INFO: HiProtoCode, MsgType = <0, e> 
2016-07-11 12:33:06,613 INFO: Create header 
2016-07-11 12:33:06,613 INFO: Packet data: 90 01 58 02 00 02 08 02 09 01 00 02 07 08 
2016-07-11 12:33:06,614 INFO: Calculate signature for packet 
2016-07-11 12:33:06,614 INFO: Calculate signature nullifier to create packet 
2016-07-11 12:33:06,615 INFO: Quote packet 
2016-07-11 12:33:06,616 INFO: Write: BD 90 01 58 02 00 02 08 02 09 01 00 02 07 08 A5 AA BD 
2016-07-11 12:33:06,616 INFO: Wait packet with transaction 1 
2016-07-11 12:33:06,635 INFO: Read packet: A8 02 70 01 08 02 00 01 09 EC 01 02 07 08 0E 27 
2016-07-11 12:33:06,635 INFO: Unquote packet 
2016-07-11 12:33:06,636 INFO: Check signature : OK 
2016-07-11 12:33:06,636 INFO: Decode packet 
2016-07-11 12:33:06,637 INFO: HiProtoCode, MsgType = <0, 9> 
2016-07-11 12:33:06,848 INFO: Create header 
2016-07-11 12:33:06,849 INFO: Packet data: 90 01 58 02 00 02 08 02 09 02 00 02 07 08 
2016-07-11 12:33:06,849 INFO: Calculate signature for packet 
2016-07-11 12:33:06,850 INFO: Calculate signature nullifier to create packet 
2016-07-11 12:33:06,851 INFO: Quote packet 
2016-07-11 12:33:06,851 INFO: Write: BD 90 01 58 02 00 02 08 02 09 02 00 02 07 08 5F 8D BD 
2016-07-11 12:33:06,852 INFO: Wait packet with transaction 2 
2016-07-11 12:33:07,010 INFO: Read packet: EF FF 10 01 0F FF 00 01 0E 00 DD F0 
2016-07-11 12:33:07,011 INFO: Unquote packet 
2016-07-11 12:33:07,011 INFO: Check signature : OK 
2016-07-11 12:33:07,012 INFO: Decode packet 
2016-07-11 12:33:07,012 INFO: HiProtoCode, MsgType = <0, e> 
2016-07-11 12:33:07,224 INFO: Create header 
2016-07-11 12:33:07,225 INFO: Packet data: 90 01 58 02 00 02 08 02 09 03 00 02 07 08 
2016-07-11 12:33:07,226 INFO: Calculate signature for packet 
2016-07-11 12:33:07,227 INFO: Calculate signature nullifier to create packet 
2016-07-11 12:33:07,227 INFO: Quote packet 
2016-07-11 12:33:07,228 INFO: Write: BD 90 01 58 02 00 02 08 02 09 03 00 02 07 08 18 70 BD 
2016-07-11 12:33:07,229 INFO: Wait packet with transaction 3 
2016-07-11 12:33:07,410 INFO: Read packet: EF FF 10 01 0F FF 00 01 0E 00 DD F0 
2016-07-11 12:33:07,411 INFO: Unquote packet 
2016-07-11 12:33:07,411 INFO: Check signature : OK 
2016-07-11 12:33:07,412 INFO: Decode packet 
2016-07-11 12:33:07,413 INFO: HiProtoCode, MsgType = <0, e> 
Traceback (most recent call last):
  File "/usr/local/bin/pycr1000", line 9, in <module>
    load_entry_point('PyCampbellCR1000==0.4', 'console_scripts', 'pycr1000')()
  File "/usr/local/lib/python2.7/dist-packages/PyCampbellCR1000-0.4-py2.7.egg/pycampbellcr1000/__main__.py", line 258, in main
    args.src_addr, args.src_node, args.code)
  File "/usr/local/lib/python2.7/dist-packages/PyCampbellCR1000-0.4-py2.7.egg/pycampbellcr1000/device.py", line 71, in from_url
    return cls(link, dest_addr, dest_node, src_addr, src_node, security_code)     #EGC Add security code to the constructor call
  File "/usr/local/lib/python2.7/dist-packages/PyCampbellCR1000-0.4-py2.7.egg/pycampbellcr1000/device.py", line 54, in __init__
    raise NoDeviceException()
pycampbellcr1000.exceptions.NoDeviceException: Can not access to device.
2016-07-11 12:33:07,644 INFO: Send bye command 

I cannot get file because it is a bug or a bad command ?

Thanks
Best regards

**Comment by VincentBourgeois** [comment]
Hello,
I have closed issue with error.
The problem is not resolved.
Do you need any other information to solve the communication ?

Thanks
Best regards

**Comment by LionelDarras** [comment]
Hi,
Can you send me details of your new text (dest_addr and node_id of yours devices, ...) and the result of script with "debug" option ?
The problem is that i can't test it with 2 CR1000 and it's why it's difficult to me to test my code in this case.
Thanks
Best regards

**Comment by VincentBourgeois** [comment]
Hi,
I have already done this test. The results are in my reply of 11 July.
Thanks
