### ISSUE TITLE
Problem When Using PyCampbellCR1000 in Python 3.x

### ISSUE THREAD

**Issue by scrambledmeggz** [LionelDarras/PyCampbellCR1000#10]
Hello.  First, thank you for writing this library!
I am getting a weird issue when using the library in Python 3.x, might I be able to get some insight in to what's going on here?
This is the callback that I get in the IDLE when I try to import the library into the scope:
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    from pycampbellcr1000 import *
  File "/home/pi/.local/lib/python3.5/site-packages/pycampbellcr1000/__init__.py", line 13, in <module>
    from .logger import LOGGER, active_logger
  File "/home/pi/.local/lib/python3.5/site-packages/pycampbellcr1000/logger.py", line 14, in <module>
    from .compat import NullHandler
  File "/home/pi/.local/lib/python3.5/site-packages/pycampbellcr1000/compat.py", line 94, in <module>
    stdout = sys.stdout.buffer
AttributeError: 'PseudoOutputFile' object has no attribute 'buffer'

Any help will be great.  Thank you!

**Comment by scrambledmeggz** [comment]
Sorry, never mind.  I was able to fix this issue by changing line 94 in .compat to the following:
    stdout = sys.__stdout__.buffer

**Comment by Makada-cyber** [comment]
Unfortunately, this didnt work for me in Windows 10.
Using python 3.8.1
