### ISSUE TITLE
Unreliable and slow serial communications on a Windows machine (with proposed fix)

### ISSUE THREAD

**Issue by agriff86** [LionelDarras/PyCampbellCR1000#21]
I have a Python script which works well from my linux machine, but from Windows it frequently drops the connection and is about a factor of 10 slower. The test machine uses Windows 10 build 1803 and a FTDI USB-Serial Driver (v2.12.36.3) with default settings.

The cause of the problem seems to be in the `read` method of `pylink.link.SerialLink`.  Due to the way an optional `timeout` argument is handled, the `read` function changes the timeout on the serial port twice, once before making the read and then a second time to change the timeout back to it's default.  All of this seems to take time, and sometimes appears to also lead to missed characters and, among other user-visible problems, truncated file transfers.

A proper fix means changing the `PyLink` library, or arguably even the driver, but since `PyCR1000` never uses the `timeout` argument, it's possible to simply ditch it and monkey patch as a work-around (also simplifying the function to avoid an unnecessary conversion from `bytes` to `str`).  The new `read` function becomes:

```Python
  def read(self, size=None):
      '''Read data from the serial connection. The maximum amount of data
      to be received at once is specified by `size`.'''
      size = size or self.MAX_STRING_SIZE
      data = self.serial.read(size)
      return data
```

A simple script which transfers the table definitions file (`.TDF`) ten times, without this patch, has the following output (the user sees a truncated file, slow transfer, and other intermittent errors)

```
C:\>python cr1000_tdf_test.py
.TDF data length: 0, acquired in 10.034833669662476 sec
.TDF data length: 3212, acquired in 3.921616315841675 sec
.TDF data length: 3212, acquired in 3.9180095195770264 sec
.TDF data length: 2048, acquired in 12.492215633392334 sec
.TDF data length: 1536, acquired in 11.8966646194458 sec
.TDF data length: 3212, acquired in 3.958491086959839 sec
.TDF data length: 512, acquired in 10.670292139053345 sec
.TDF data length: 0, acquired in 10.043192863464355 sec
Traceback (most recent call last):
  File "test_cr1000_forpatch.py", line 72, in <module>
    tdfdata = cr1000.getfile(".TDF")
  File "C:\Data\working\2020-03-radon-monitor-software\radon-monitor-gui\venv\lib\site-packages\pycampbellcr1000\device.py", line 133, in getfile
    self.ping_node()
  File "C:\Data\working\2020-03-radon-monitor-software\radon-monitor-gui\venv\lib\site-packages\pycampbellcr1000\device.py", line 90, in ping_node
    raise NoDeviceException()
pycampbellcr1000.exceptions.NoDeviceException: Can not access to device.
```

With the patch, data transfer is reliable and much faster:

```
C:\>python cr1000_tdf_test.py
.TDF data length: 3212, acquired in 0.6098387241363525 sec
.TDF data length: 3212, acquired in 0.5850188732147217 sec
.TDF data length: 3212, acquired in 0.6093173027038574 sec
.TDF data length: 3212, acquired in 0.6357443332672119 sec
.TDF data length: 3212, acquired in 0.6329364776611328 sec
.TDF data length: 3212, acquired in 0.6290316581726074 sec
.TDF data length: 3212, acquired in 0.6395828723907471 sec
.TDF data length: 3212, acquired in 0.6402559280395508 sec
.TDF data length: 3212, acquired in 0.6247656345367432 sec
.TDF data length: 3212, acquired in 0.615476131439209 sec
```

My Python version is 3.6.3, pyserial 3.5, pylink 0.3.3 (latest from PyPi), pycampbellcr1000 0.4dev (latest from PyPi).

Here's the complete script demonstrating the problem and workaround (requires a datalogger - I've tested with a CR800 and CR1000):

```Python
import time

SERIAL_PORT = "COM5"
DO_THE_PATCH = True

# Monkey patching
# - return data from SerialLink as bytes (without conversion to str) and
# - without any adjustments to the timeout
#
# On my test machine (Windows 10 build 1803, FTDI USB-Serial Driver 2.12.36.3 with 
# the default settings) adjusting the timeout in this function seems to be the cause
# of problems, including: lost data and a 10x slowdown in data transfer.
# These problems are not observed when using the same FTDI dongle running from a Linux
# box or (strangely) when running from WSL.
#
# Since the timeout argument is never used from PyCampbellCR1000, let's just simplify
# this function.
#
# Here is what we are replacing (as an aside, the docstring refers to a missing function argument):
    # def read(self, size=None, timeout=None):
    #     '''Read data from the serial connection. The maximum amount of data
    #     to be received at once is specified by `size`. If `is_byte` is True,
    #     the data will be convert to byte array.'''
    #     size = size or self.MAX_STRING_SIZE
    #     timeout = (timeout or 1) * (self.timeout or 1)
    #     self.serial.timeout = timeout
    #     data = self.serial.read(size)
    #     try:
    #         data = str(data, encoding='utf8')
    #     except:
    #         pass
    #     if len(data) != 0 :
    #         self.log("Read", data)
    #     self.serial.timeout = self.timeout
    #     return data
def read_bytes_but_do_not_mess_with_timeout(self, size=None):
    '''Read data from the serial connection. The maximum amount of data
    to be received at once is specified by `size`.'''
    size = size or self.MAX_STRING_SIZE
    data = self.serial.read(size)
    return data

if DO_THE_PATCH:
    # Monkey-patch the PyLink library
    import pylink
    pylink.link.SerialLink.read = read_bytes_but_do_not_mess_with_timeout

# ... test
from pycampbellcr1000 import CR1000
cr1000 = CR1000.from_url(f"serial:{SERIAL_PORT}:115200")
for ii in range(10):
    tick = time.time()
    # Obtain the table definitions
    tdfdata = cr1000.getfile(".TDF")
    tock = time.time()
    print(f".TDF data length: {len(tdfdata)}, acquired in {tock-tick} sec")
```

**Comment by agriff86** [comment]
An even simpler work-around is possible.  Instead of using `from_url`, you can use the `CR1000` constructor.  Instead of passing a `PyLink` object, pass it a pySerial `serial.Serial` object which has not yet been opened.

That is, instead of this:

```Python
import serial
from pycampbellcr1000 import CR1000

cr1000 = CR1000.from_url("serial:COM5:115200", timeout=2)
```

try this:

```Python
import serial
from pycampbellcr1000 import CR1000

# use port=None to create a serial port object without opening the underlying port
ser = serial.Serial(port=None, 
                    baudrate=115200,
                    timeout=2,
                    bytesize=serial.EIGHTBITS,
                    parity=serial.PARITY_NONE,
                    stopbits=1)
ser.port = "COM5"
cr1000 = CR1000(ser)
```

**Comment by playertr** [comment]
I also ran into this issue and @agriff86 's workaround worked for me. Thank you!
